### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by yanniboi** [yanniboi/CorgiHero#4]
This is the list of features we want.

### Corgi/Hero2D

**MVP**
- [ ] Movement (Idle/Walk/Run) #5
- [ ] Jump (/double jump) - #3 
- [ ] Tutorials - #6

**Full Hero Features**

- [ ] Crouching
- [ ] Climbing
- [ ] Death
- [ ] Weapons

**Full Corgi Features**

- [ ] Looking up
- [ ] Dashing
- [ ] Dangling
- [ ] Activating
- [ ] Crawling
- [ ] Taking Damage
- [ ] Swimming (/Diving)
- [ ] Pulling (/Pushing/Gripping)
- [ ] Wall clinging (/Wall jumping)
- [ ] Flying (/Jetpacking/Gliding)

### TopDown/Hero4D

**MVP**
- [ ] Movement4D (Idle/Walk/Run/Ready) - #1 
- [ ] Tutorials - #7

**Full Hero4D Features**

- [ ] Crouching
- [ ] Jump
- [ ] Climbing
- [ ] Block
- [ ] Weapons

**Full TopDown Features**

- [ ] Death
- [ ] Looking up
- [ ] Dashing
- [ ] Activating
- [ ] Crawling
- [ ] Falling down hole
- [ ] Taking Damage

**Comment by bouchaibcharioui** [comment]
Hello yanniboi. Firstable, thank yo for your efforts.
I have a request if you don't mind. Could you please make a video Tutorial on YouTube or elsewhere where you show the step by step integration between Corgi Engine & Character Editor?

Thank you so much again.
